apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-app-chart.fullname" . }}
spec:
  replicas: {{ .Values.webApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "web-app-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "web-app-chart.name" . }}
    spec:
      containers:
        - name: web-app
          image: "{{ .Values.webApp.image.repository }}:{{ .Values.webApp.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: MYSQL_PORT
              value: {{ .Values.mysql.port | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webApp.service.name }}
spec:
  selector:
    app: {{ include "web-app-chart.name" . }}
  ports:
    - port: {{ .Values.webApp.service.port }}
      targetPort: 8080
  type: {{ .Values.webApp.service.type }}
