# Dockerfile for the web application
FROM golang:alpine3.18 AS builder

WORKDIR /app

COPY . .

RUN go build -o web-app .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/web-app .

CMD ["./web-app"]
